import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Oxanium } from "next/font/google";

import { ThemeProvider } from "~/app/_components/theme-provider";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const oxanium = Oxanium({
  subsets: ["latin"],
  variable: "--font-oxanium",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${oxanium.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
          // Map each theme to an explicit class so next-themes ADDS `.light`
          // (not just removes `.dark`). Required because `:root` carries the dark
          // palette as the no-flash default, so light mode must apply its own class.
          value={{ light: "light", dark: "dark" }}
        >
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ThemeProvider>
        <div className="retro-overlay" aria-hidden />
      </body>
    </html>
  );
}
